### PR TITLE
Revert sv2v changes from tlul_socket_m1 modules

### LINKED ISSUE #324: Earlgrey: yosys fails to parse tlul_socket_m1
``tlul_socket_m1`` module was moved to Surelog by replacing it context with code generated using sv2v.
Trying to use original module prints error in yosys: 
```
ERROR: Index in generate block prefix syntax is not constant!
```

### PR DESCRIPTION
**Pull request by kamilrakoczy**
This PR reverts changes from tlul_socket_m1 modules and moves them to UHDM.

Fixes: https://github.com/alainmarcel/uhdm-integration/issues/324

### CODE REVIEW

File: passes/sat/freduce.cc [hunk 1]
```diff
@@ -27,6 +27,7 @@
 #include <stdio.h>
 #include <string.h>
 #include <algorithm>
+#include <limits>
```
Comment (kbieganski) [inline passes/sat/freduce.cc:30]: Is this include needed?

Comment (kamilrakoczy) [reply passes/sat/freduce.cc:30]: Yes it is, gcc version in GH-actions changed (example failure in dependabot PR: https://github.com/antmicro/yosys/pull/320/checks?check_run_id=2601015215#step:5:1471), and now limits needs to be include explicitly (see: https://gcc.gnu.org/gcc-11/porting_to.html).

It is already fixed on mainstream yosys.

**Review by kbieganski — APPROVED** [review]
